---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates
- cluster-issuers
components:
- ../components/helm-release-crds-label
- ../components/helm-release-remediation-label
