name: Compile and publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  compile-and-publish:
    name: Compile and publish
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‘ Checkout
        uses: actions/checkout@v4
      - name: âš™ï¸ Setup shc
        run: |
          sudo add-apt-repository ppa:neurobin/ppa
          sudo apt-get update -y
          sudo apt-get install shc -y
      - name: ğŸ“¦ Compile
        run: |
          shc -f ksail.sh -o ksail
      - name: ğŸ“¦ Publish
        uses: softprops/action-gh-release@v1
        with:
          files: ksail
