name: Compile and publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  compile-and-publish:
    name: Compile and publish
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‘ Checkout
        uses: actions/checkout@v4
      - name: âš™ï¸ Setup shc
        run: |
          sudo apt-get update
          sudo apt-get install shc
      - name: âœğŸ» Update version
        run: perl -i -pe 's/VERSION=.*/VERSION="${{ github.ref_name }}"/g' ksail.sh

      - name: ğŸ”¨ Compile
        run: |
          shc -f ksail.sh -o ksail
      - name: ğŸ“¦ Publish
        uses: softprops/action-gh-release@v1
        with:
          files: ksail
