name: Readme Tree

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tree:
    runs-on: ubuntu-latest
    name: readme-tree
    steps:
      - uses: actions/checkout@v4
      - name: Create README Tree
        uses: RavelloH/readme-tree@v1.1.0
        with:
          showdirectoryname: "yes"
      - name: Generate GitHub App Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-readme-tree
          commit-message: Update README Tree
          title: Update README Tree
          body: This PR includes new updates to the README Tree.
          labels: chore
          token: ${{ steps.generate-token.outputs.token }}
